// <auto-generated />
namespace External.RadProApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class rgitr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rgitr));
        
        string IMigrationMetadata.Id
        {
            get { return "201910130226409_rgitr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
